AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: AuthToken
        Authorizers:
          AuthToken:
            FunctionArn: !GetAtt AuthToken.Arn
          AuthRequest:
            FunctionArn: !GetAtt AuthRequest.Arn
            FunctionPayloadType: REQUEST
            Identity:
              Headers:
              - Authorization

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: ./hello
      Handler: handler.hello
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /hello
            Method: GET

  AuthToken:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: ./token
      Handler: handler.authorize

  AuthRequest:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: ./request
      Handler: handler.authorize

Outputs:
  Region:
    Value: !Ref AWS::Region

  ApiId:
    Value: !Ref MyApi

  ApiUrl:
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/'
